scrape_configs:
  - job_name: reg-ru-server
    scrape_interval: 5s
    static_configs:
      - targets:
          - 194.58.122.46:9100

  - job_name: vpn-server
    scrape_interval: 5s
    static_configs:
      - targets:
          - 77.105.143.98:9100

  - job_name: at-first-sight
    scrape_interval: 5s
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - kundin.pro
